#%RAML 1.0 DataType
type: object
properties: 
  ItemName:
    description: The item name
    required: true
    type: string
  ItemCost: 
    description: The item cost
    required: true
    type: number
  ItemID: 
    description: The item id
    required: true
    type: number